### ISSUE TITLE
Breaking change made in Iris

### ISSUE THREAD

**Issue by sp1at** [iris-contrib/cloud-native-go#2]
Iris made a breaking change which in turn leads to a failure in `make docker`. The issue is  discussed [here](https://github.com/kataras/iris/issues/1385#issuecomment-547136757).
the output of `make docker` is:

```
# github.com/kataras/iris/core/errgroup
src/github.com/kataras/iris/core/errgroup/errgroup.go:109:9: undefined: errors.Unwrap
src/github.com/kataras/iris/core/errgroup/errgroup.go:118:8: undefined: errors.Is
src/github.com/kataras/iris/core/errgroup/errgroup.go:125:10: undefined: errors.Is
src/github.com/kataras/iris/core/errgroup/errgroup.go:137:8: undefined: errors.As
src/github.com/kataras/iris/core/errgroup/errgroup.go:150:10: undefined: errors.As
# github.com/kataras/iris/context
src/github.com/kataras/iris/context/context.go:2859:6: undefined: errors.Is
```

**Comment by kataras** [comment]
No @sp1at  this is not the same issue, here you have that because the `Dockerfile` uses go 1.10. This one uses go version less than 1.13 throws that error.  See here:

https://github.com/iris-contrib/cloud-native-go/blob/713d6351163d8452c4b2c48ecf1798176a2f562c/Dockerfile#L1

The `errors.Is/As` are introduced on **go1.13**, I'll update it to use apline 1.13 and it will be fixed. If you check the rest of the code and tools you will see they are up-to-dated.

**Comment by sp1at** [comment]
Great - thanks @kataras. I didn't think to check the version.

**Comment by kataras** [comment]
No problem @sp1at, you are welcome and thanks for the report!

-------------

If you like what you see please star this repository and the [iris](https://github.com/kataras/iris) one, it's a simple step to show your support and appreciation.
